---
- hosts: localhost 
  become: true
  gather_facts: false
  vars:
    param_repo_base: "http://www.opentlc.com/download/ansible_bootcamp"
    param_user: "sarasubb-in.ibm.com"
    param_password: "BigB0ss1fdb2@19"
  tasks:
    - name: create bin directory
      file:
        path: /tmp/bin
        state: directory
    - name: get script common.sh
      get_url:
        url: "{{ param_repo_base }}/scripts/common.sh"
        dest: /tmp/common.sh
        mode: 0755

    - name: get script jq
      get_url: 
        url: "{{ param_repo_base }}/scripts/jq-linux64"
        dest: /tmp/bin/jq
        mode: 0755
    - name: get script order_svc.sh
      get_url:
        url: "{{ param_repo_base }}/scripts/order_svc.sh"
        dest: /tmp/order_svc.sh
        mode: 0755
    - name: create credentials
      copy:
        content: |
          export username={{ param_user }}
          export password={{ param_password }}
          export uri=https://labs.opentlc.com
        dest: /tmp/aws_credential.rc
        mode: 0755

    # Fix the existing shell scripts to reference jq command with bin/jq
    - name: fix scripts
      shell: "sed -i 's/ jq/ bin\\/jq/g' {{ item }}"
      with_items:
        - /tmp/common.sh
        - /tmp/order_svc.sh

    # Using this script will always deploy environments in the us-east-1 region.
    # TODO: this shell task is not working yet!
    - name: order service on opentlc
      shell: source /tmp/aws_credential.rc; ./order_svc.sh -y -c 'OPENTLC Automation' -i 'Ansible Advanced - Three Tier App' -t 1 -d 'dialog_expiration=7;region=na;nodes=1;dialog_runtime=8;notes=Training - As part of course'
      args:
        chdir: /root
    - name: Wait for mail
      pause:
        minutes: 10 
